version: '3.7'

services:
  sonic:
    image: valeriansaliou/sonic:v1.3.0
    ports:
      - 1491:1491
    volumes:
      - ./sonic/sonic.cfg:/etc/sonic.cfg
      - ./sonic/store/:/var/lib/sonic/store/
